name: CI

on:
  push:
    branches:
      - master
env:
  cache-version: v1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ env.cache-version }}-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-node-
 
      - name: Npm install
        run: npm i

      - name: Run test
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Global install firebase-tools
        run: npm i -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: npm run deploy -- --token=${{ secrets.FIREBASE_TOKEN }}
